### ISSUE TITLE
SSMS 2016+ on Windows Azure VM

### ISSUE THREAD

**Issue by OkomelaIT** [gandarez/ssms-wakatime#12]
This is a combination of the issues relating to SSMS version 2016 and later whereby the reference to HKEY_CURRENT_USER\Software\Microsoft\SQL Server Management Studio\11.0_Config\AutomationOptions\LookInFolders and C:\Users\\AppData\Roaming\Microsoft\MSEnvShared\Addins is not pertinent.

In short the question is how do we get Wakatime to work in these environments for SSMS. The work around I am employing at present is to create database projects in Visual Studio to do my SQL work. However this does not compare to running SQL queries in SSMS

**Comment by gandarez** [comment]
Just released a new version to support v2012+

Download and follow the instructions
https://github.com/gandarez/ssms-wakatime/releases/tag/v2.0.0
