### ISSUE TITLE
Cannot add API key for SSMS 

### ISSUE THREAD

**Issue by frackham** [gandarez/ssms-wakatime#14]
With release 2, SSMS 2017:

1. Downloaded 
2. Followed instructions here: https://github.com/gandarez/ssms-wakatime
(particularly copying WakaTime folder to C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\ManagementStudio\Extensions ), including running the batch file.
3. Was not asked for API key, not clear where to input.

Microsoft SQL Server Management Studio						14.0.17289.0
Microsoft Analysis Services Client Tools						14.0.1016.283
Microsoft Data Access Components (MDAC)						10.0.17134.1
Microsoft MSXML						3.0 6.0 
Microsoft Internet Explorer						9.11.17134.0
Microsoft .NET Framework						4.0.30319.42000
Operating System						6.3.17134

**Comment by gandarez** [comment]
Are you a returning user or have installed another extension in your machine?

**Comment by frackham** [comment]
Installed this extension via zip --> folder and executing batch. There do not seem to be any other installation steps?

**Comment by frackham** [comment]
Sorry, I have tried using this before, but new local machine so should be a clean install.

**Comment by gandarez** [comment]
The api key will be asked only if you're isntalling WakaTime for the very first time
