### ISSUE TITLE
Wakatime does not log

### ISSUE THREAD

**Issue by hubbardsw** [gandarez/ssms-wakatime#16]
Newest extension release for SSMS 2017 installs fine but does not log at all

**Comment by gandarez** [comment]
@hubbardsw  it has been tested under SSMS 2016 and there wasn't any error. Could you please share your ActivityLog.xml file?

**Comment by hubbardsw** [comment]
I got it, had to unblock the .dll

**Comment by StevenNell** [comment]
Hi There,

Where can I find the activitylog.xml? Mine is also not showing up on my dashboard.

Installed previously on Chrome and Visual Studio 
Microsoft SQL Server Management Studio						12.0.2269.0
Microsoft Analysis Services Client Tools						12.0.2000.8
Microsoft Data Access Components (MDAC)						10.0.17763.1
Microsoft MSXML						3.0 5.0 6.0 
Microsoft Internet Explorer						9.11.17763.0
Microsoft .NET Framework						4.0.30319.42000
Operating System						6.3.17763

**Comment by w371987114** [comment]
> Hi There,
> 
> Where can I find the activitylog.xml? Mine is also not showing up on my dashboard.
> 
> Installed previously on Chrome and Visual Studio
> Microsoft SQL Server Management Studio	12.0.2269.0
> Microsoft Analysis Services Client Tools	12.0.2000.8
> Microsoft Data Access Components (MDAC)	10.0.17763.1
> Microsoft MSXML	3.0 5.0 6.0
> Microsoft Internet Explorer	9.11.17763.0
> Microsoft .NET Framework	4.0.30319.42000
> Operating System	6.3.17763

you can use listary or everything to find this file
In my computer,It's location is `C:\Users\[YourUser]\AppData\Roaming\Microsoft\AppEnv\14.0`
