### ISSUE TITLE
Can not load WakaTimePackage in ssms 2017.8.1

### ISSUE THREAD

**Issue by w371987114** [gandarez/ssms-wakatime#17]
I follow [this](https://wakatime.com/sql-server-management-studio) step to install it
and when I start my ssms,I get this error
![image](https://user-images.githubusercontent.com/17959236/58072267-bc5b6b80-7bd1-11e9-95a8-59054ce670f6.png)
and this is my ActivityLog.xml
[ActivityLog.zip](https://github.com/gandarez/ssms-wakatime/files/3201001/ActivityLog.zip)
this is my ssms about page
![image](https://user-images.githubusercontent.com/17959236/58072361-080e1500-7bd2-11e9-8ef3-7d73e0ca5211.png)
and I use another extension:SQLPrompt,I don't know whether it cause this error

**Comment by w371987114** [comment]
I open the ActivityLog.xml,and I search the guid of 52d9c3ff-c893-408e-95e4-d7484ec7fa47
I can find this error`Appid denied the loading of package`
so,I try to run the ssms with administrator，and now it works well
So, I suggest you write `run the ssms with administrator` note in the [install step](https://wakatime.com/sql-server-management-studio) as  tips

**Comment by gandarez** [comment]
Thank @w371987114 I already added the troubleshooting section and will make a PR to website.
