### ISSUE TITLE
Can not record the right editor

### ISSUE THREAD

**Issue by w371987114** [gandarez/ssms-wakatime#18]
I have used this plugin for two days.
I used to think that it couldn't record data; today, I use debug mode to see its commands; I also saw the recorded file information on the dashboard; but in the editor this column does not show ssms, I also see the command Written in visual studio, so I think there is a problem with the command sent by this plugin.
![image](https://user-images.githubusercontent.com/17959236/58230745-c7e09b00-7d67-11e9-88e1-ba1df399f234.png)
and I think this is the problem
![image](https://user-images.githubusercontent.com/17959236/58230831-08401900-7d68-11e9-980e-aa9e9efa2016.png)

**Comment by gandarez** [comment]
Thanks for pointing that I already fixed with release 2.0.1
