### ISSUE TITLE
Have failed install of 1.0.3 for SSMS 2014 still creating issues, what do I clean up to install 2.0.1?

### ISSUE THREAD

**Issue by jnickle** [gandarez/ssms-wakatime#21]
Posted original issue a year ago at the now closed issue: https://github.com/gandarez/ssms-wakatime/issues/1   Original attempted install was version 1.0.3

Help!? Re the post referenced above, I did get past that step, but could never get past the "install python" prompt. Gave up. lived with the "install python" popup every time I open SSMS since then. Now I'm circling back and seeing new install steps. Seems much quicker, easier, etc. I was hoping that following these instructions for v 2.0.1 for SSMS 2014 would "override/overwrite" problems with my previous install attempt, sadly it didn't. ... can anyone provide instructions on what I need to back out to make the new install work? I've got wakatime.cfg & .db & .log in my C:\Users<user> folder. Do I keep these? What about the WakaTime.Addin and WakaTime.dll files in C:\users\xxxxxx\AppData\Roaming\Microsoft\MSEnvShared\Addins\ ?? Any others? I really want this tool to work, any advice greatly appreciated.

**Comment by gandarez** [comment]
The extension has been bumped to version `3.0.0`. Please follow the updated instructions on README to reinstall it.
