### ISSUE TITLE
Error - Won't load with SSMS 2019.150.18142.0 (v18.2)

### ISSUE THREAD

**Issue by KrunchMuffin** [gandarez/ssms-wakatime#22]
![image](https://user-images.githubusercontent.com/1037197/64030667-03cc8e80-cb15-11e9-875e-bdf66b9de1c3.png)
![image](https://user-images.githubusercontent.com/1037197/64030730-2363b700-cb15-11e9-9e0d-42a7e3df485f.png)
[ActivityLog.zip](https://github.com/gandarez/ssms-wakatime/files/3560423/ActivityLog.zip)

**Comment by lastowl** [comment]
To fix this go to the wakatime.dll, right click properties  and click unblock then okay and it’ll work on restart
