### ISSUE TITLE
Not requested API Key

### ISSUE THREAD

**Issue by odskee** [gandarez/ssms-wakatime#23]
Possible duplicate issue; WakaTime isn't asking for an API key on startup.  I've followed the latest instructions for installation and have run the .bat and tried SSMS as admin.

Console shows the following during startup so it appears the extension is being loaded; I just have no idea where you're meant to put the API key?

[WakaTime Info 03:47:09 PM] Initializing WakaTime v2.0.1
[WakaTime Info 03:47:10 PM] Current wakatime-cli version is 13.0.2
[WakaTime Info 03:47:10 PM] Checking for updates to wakatime-cli...
[WakaTime Info 03:47:10 PM] wakatime-cli is up to date.
[WakaTime Info 03:47:10 PM] Finished initializing WakaTime v2.0.1

I'm using the following version:
SQL Server Management Studio						15.0.18206.0
Microsoft Analysis Services Client Tools						15.0.1567.0
Microsoft Data Access Components (MDAC)						10.0.18362.1
Microsoft MSXML						3.0 6.0 
Microsoft Internet Explorer						9.11.18362.0
Microsoft .NET Framework						4.0.30319.42000
Operating System						10.0.18362

**Comment by Koynonia** [comment]
To fix this go to the wakatime.dll, right click properties and click unblock then okay and it’ll work on restart.

In the menu choose "Tools" > "Wakatime"

![image](https://user-images.githubusercontent.com/1801285/72167433-e1435f80-33a9-11ea-8bf5-7f8afab539cc.png)

**Comment by gandarez** [comment]
@odskee does that fixed for you?

**Comment by badmark** [comment]
I followed this, I was able to enter the API key, but it still does not report to my dashboard?

**Comment by badmark** [comment]
I am using Visual Studio (2019) and SSMS (v18.4), Visual Studio actions get logged, but anything done in SMSS returns an error, "File does not exist; ignoring this heartbeat."

{"now": "2020/04/09 15:27:16 -0400", "version": "13.0.7", "plugin": "ssms/2019.0150 ssms-wakatime/2.0.1", "time": 1586460432.518643, "caller": "C:\\Users\\User\\AppData\\Roaming\\WakaTime\\wakatime-master\\wakatime\\main.py", "lineno": 70, "is_write": true, "file": "Server[@Name='PC-W10WKS']/Database[@Name='db_bd']/View[@Name='vw_BusinessLocationProductStock' and @Schema='dbo']", "level": "DEBUG", "message": "File does not exist; ignoring this heartbeat."}

**Comment by ErivandoBR** [comment]
SSMS v18.10 is not working.

Api Key is OK, but it doesn't register in the dashboard.

Visual Studio and others are working.

**Comment by gandarez** [comment]
The extension has been bumped to version `3.0.0`. Please follow the updated instructions on README to reinstall it.
