### ISSUE TITLE
Wakatime doesnt load/install in SSMS 17.9

### ISSUE THREAD

**Issue by dillardj** [gandarez/ssms-wakatime#24]
I've followed the directions for installing wakatime in SSMS but I'm not getting the item in the Tools tab nor am I see any errors:
![image](https://user-images.githubusercontent.com/30057207/99005932-882ae780-24f6-11eb-879f-b22dd0994748.png)

Not sure what to do at this point.

**Comment by gandarez** [comment]
The extension has been bumped to version `3.0.0`. Please follow the updated instructions on README to reinstall it.
