### ISSUE TITLE
waka time not working in SSMS v17.8.1

### ISSUE THREAD

**Issue by pamanes** [gandarez/ssms-wakatime#25]
hi, I followed the instructions but absolutely nothing is happening when I open SSMS. I changed the wakatime.cfg debug flag to true but nothing is logged about SSMS.

I ran the AddPackage.bat then copied the WakaTime folder to: C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\ManagementStudio\Extensions

please help, this is my SSMS about:

Microsoft SQL Server Management Studio            14.0.17277.0
Microsoft Analysis Services Client Tools			14.0.1016.262
Microsoft Data Access Components (MDAC)		10.0.18362.1
Microsoft MSXML						        3.0 6.0 
Microsoft Internet Explorer					9.11.18362.0
Microsoft .NET Framework					4.0.30319.42000
Operating System						        6.3.18363

thanks,

**Comment by minoveaz** [comment]
I did this to solve the problems check this issue:  https://github.com/gandarez/ssms-wakatime/issues/28

**Comment by gandarez** [comment]
The extension has been bumped to version `3.0.0`. Please follow the updated instructions on README to reinstall it.
