### ISSUE TITLE
How to set Project Name

### ISSUE THREAD

**Issue by alexvremja** [gandarez/ssms-wakatime#27]
Hi!

I installed the plugin on SSMS 18.8, it works, but 
it attribute the time to "Unknown Project" and file name is something like "~vsA005.sql"
how can I set project name?
I tried adding a ".wakatime-project" file containing the name of the project in the same directory where are stored primary and log database file but it still not works.

Thanks

**Comment by alanhamlett** [comment]
The best way is use Git for your project folder with `git init`, and here's a list of all the ways project names are detected:
https://wakatime.com/faq#rename-projects

**Comment by gandarez** [comment]
Any update here @alexvremja?
