### ISSUE TITLE
Problems Configurating WakaTime in SSMS18 - SOLVED

### ISSUE THREAD

**Issue by minoveaz** [gandarez/ssms-wakatime#28]
I have follow these steps to be able to configurate: 

1. Download the latest release https://github.com/gandarez/ssms-wakatime/releases/latest
2. Unzip the content.
3. Run AddPackage.bat to add WakaTime extension into registry white list.
4. Open SSMS and select option No 
![image](https://user-images.githubusercontent.com/9484731/113716735-2f4d2d00-96eb-11eb-909b-8883012ff2cf.png)
5. Close SSMS
6. Follow this step https://github.com/gandarez/ssms-wakatime/issues/23#issuecomment-573096967 
> To fix this go to the wakatime.dll, right click properties and click unblock then okay and it’ll work on restart.
> 
> In the menu choose "Tools" > "Wakatime"
> 
> ![image](https://user-images.githubusercontent.com/1801285/72167433-e1435f80-33a9-11ea-8bf5-7f8afab539cc.png)

7. Start SSMS and right here the WakaTime extension should appear so you can add your API Key 
8. It also appears in the Tools window 

![image](https://user-images.githubusercontent.com/9484731/113717445-e9dd2f80-96eb-11eb-91f3-6323fac05f0d.png)
9. Now it is working 

![image](https://user-images.githubusercontent.com/9484731/113718033-8b648100-96ec-11eb-82da-0860609a16f1.png)
![image](https://user-images.githubusercontent.com/9484731/113718124-9fa87e00-96ec-11eb-8e67-ca96e21b8307.png)

**Comment by WilkieIT** [comment]
This resolved my issue in SSMS 18.9.1

Thanks

**Comment by gandarez** [comment]
The extension has been bumped to version `3.0.0`. Please follow the updated instructions on README to reinstall it.
