### ISSUE TITLE
Which SSMS versions should this support?

### ISSUE THREAD

**Issue by charliewynn** [gandarez/ssms-wakatime#3]
I have SSMS 10.50.1600.1 (sql server 2008 R2) and my registry layout is completely different from the suggested install.

I don't have     HKEY_CURRENT_USER\Software\Microsoft\SQL Server Management Studio...
Instead mine's HKEY_CURRENT_USER\Software\Microsoft\Microsoft SQL Server

The 11.0_Config makes me think this is designed for a higher version than I have.

**Comment by gandarez** [comment]
Express editions is not fully tested.
