### ISSUE TITLE
Wrong file path for python CLI

### ISSUE THREAD

**Issue by tomHaum** [gandarez/ssms-wakatime#30]
> [WakaTime Debug 03:22:12 PM] ["\python27\pythonw", "C:\Users\xxxx\AppData\Roaming\WakaTime\wakatime-master\wakatime\cli.py", "--key", "XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXX1c51", "--entity", "C:\Users\xxxx\AppData\Local\Temp\~vsA096.sql", "--time", "1644351732.178587", "--plugin", "ssms/2019.0150 ssms-wakatime/2.0.1"]
[WakaTime Debug 03:22:12 PM] \python27\pythonw: can't open file 'C:\Users\xxxx\AppData\Roaming\WakaTime\wakatime-master\wakatime\cli.py': [Errno 2] No such file or directory

I went to `C:\Users\xxxx\AppData\Roaming\` and noticed a folder named `legacy-python-cli-master`. I made a copy of this named `wakatime-master` and then the plugin started working again. Im guessing the repository names changed or something? not too sure but im suspicious of https://github.com/gandarez/ssms-wakatime/blob/master/WakaTime/Constants.cs#L16 and https://github.com/gandarez/ssms-wakatime/blob/8010b6ee0c85f343ac1d6b5bf5b5c5e3385ffcd9/WakaTime/Dependencies.cs#L43. Just tried downloading `https://github.com/wakatime/wakatime/archive/master.zip` myself and i got a file called `legacy-python-cli-master.zip`

**Comment by gandarez** [comment]
The extension has been bumped to version `3.0.0`. Please follow the updated instructions on README to reinstall it.
