### ISSUE TITLE
Any development on SQL Server Management Studio 19 in the pipeline?

### ISSUE THREAD

**Issue by PorkChopGuru** [gandarez/ssms-wakatime#32]
Currently testing SQL Server Management Studio 19 Preview 3, current v18 does not play nicely with v19.

**Comment by slurpo** [comment]
Yes, the version 19 is not working with SSMS. 
Please add the compatibility.

**Comment by gandarez** [comment]
Added support for v19 with https://github.com/gandarez/ssms-wakatime/releases/tag/v4.0.0
