### ISSUE TITLE
SSMS not prompting for my wakatime API

### ISSUE THREAD

**Issue by gail-bowen-bgc** [gandarez/ssms-wakatime#4]
https://wakatime.com/help/plugins/sql-server

I followed the steps in the URL above, but I see no sign of WakaTime in SSMS. I was expecting it to prompt for my WakaTime API.

**Comment by alanhamlett** [comment]
First, do you have any other WakaTime plugins installed? The plugins share a common config file at `~/.wakatime.cfg` so this plugin won't prompt if an api key is already in that file.

**Comment by gail-bowen-bgc** [comment]
I do. WakaTime hasn't recorded any of my SQL work yet, but maybe there is a small delay. I'll check it again tomorrow morning.

**Comment by gail-bowen-bgc** [comment]
It's still not recording any SQL coding.

**Comment by gandarez** [comment]
@gail-bowen-bgc is it recording now? What's SSMS version you're using for?

**Comment by gail-bowen-bgc** [comment]
It recorded 1 minute for last week, which can’t be right. I’m using 2012:

Microsoft SQL Server Management Studio                                                                                            11.0.2100.60
Microsoft Data Access Components (MDAC)                                                                                        10.0.10586.0
Microsoft MSXML                                                                                            3.0 6.0
Microsoft Internet Explorer                                                                                         9.11.10586.0
Microsoft .NET Framework                                                                                          4.0.30319.42000
Operating System                                                                                            6.3.10586

[cid:image008.jpg@01D19CA6.4F5CC8C0]
Gail Bowen
.NET Developer
Bluegrasscoms Ltd, Construction House, Winchester Road, Burghclere, Newbury, Hampshire, RG20 9EQ
Tel. +44 (0) 844 247 3577
Fax. 0118 916 5398
Email. gail.bowen@bluegrasscoms.com<mailto:gail.bowen@bluegrasscoms.com>
Web. www.bluegrasscoms.com<http://bluegrasscoms.com/>
[cid:image003.jpg@01D19CA3.6A8A35E0]<https://www.facebook.com/bluegrasscoms>[cid:image004.jpg@01D19CA3.6A8A35E0]<https://twitter.com/Bluegrasscoms> [cid:image005.jpg@01D19CA3.6A8A35E0] <https://www.linkedin.com/company/2401710?trk=prof-exp-company-name>

[cid:image009.jpg@01D19CA6.4F5CC8C0]

---
This e-mail may contain confidential and/or privileged information. If you are not the
intended recipient (or have received this e-mail in error) please notify the sender
immediately and destroy the e-mail. Any unauthorized copying, disclosure or distribution
of the material in this e-mail is strictly forbidden.

**Comment by gandarez** [comment]
It does not make sense at all. 
I've been using SSMS 2012 all the time and have gotten recorded everything!

@alanhamlett any thoughts?

**Comment by alanhamlett** [comment]
I have no idea what could be preventing logging without an error message from the `idea.log` or `~/.wakatime.log` file. @gail-bowen-bgc can you turn on debug mode in your WakaTime settings menu, then check those log files?

https://github.com/wakatime/wakatime#troubleshooting
https://intellij-support.jetbrains.com/hc/en-us/articles/207241085-Locating-IDE-log-files

**Comment by cgaete** [comment]
where put API Key?? 
Regards

**Comment by alanhamlett** [comment]
@cgaete you should have a `WakaTime Settings` menu in either the `File` or `Tools` menu.

**Comment by FBlade** [comment]
WakaTime menu exists
![image](https://cloud.githubusercontent.com/assets/6547619/26037684/a2c49d3e-38f0-11e7-9d0b-fe518e1678b2.png)

...however, after click, item turns to disabled, but nothing happens... Stil cant set API KEY
![image](https://cloud.githubusercontent.com/assets/6547619/26037693/c89923ea-38f0-11e7-9f15-81e62538bd9e.png)

**Comment by cgaete** [comment]
Thanks!

**Comment by Crysalist** [comment]
I have same issue - the wakatime menu shows under my tools but It is greyed out / disabled. So cannot change / set my api key

**Comment by Crysalist** [comment]
Fixed it by adding config file in C:\Users\USERNAME\ with these settings:
`[settings]
api_key =API_KEY_HERE
debug =false
proxy=
`

**Comment by badmark** [comment]
I am using Visual Studio (2019) and SSMS (v18.4), Visual Studio actions get logged, but anything done in SMSS returns an error, "File does not exist; ignoring this heartbeat."

`{"now": "2020/04/09 15:27:16 -0400", "version": "13.0.7", "plugin": "ssms/2019.0150 ssms-wakatime/2.0.1", "time": 1586460432.518643, "caller": "C:\\Users\\User\\AppData\\Roaming\\WakaTime\\wakatime-master\\wakatime\\main.py", "lineno": 70, "is_write": true, "file": "Server[@Name='PC-W10WKS']/Database[@Name='db_bd']/View[@Name='vw_BusinessLocationProductStock' and @Schema='dbo']", "level": "DEBUG", "message": "File does not exist; ignoring this heartbeat."}`
