### ISSUE TITLE
Correct folder for WakaTime.Addin

### ISSUE THREAD

**Issue by alanhamlett** [gandarez/ssms-wakatime#7]
Where should the `WakaTime.Addin` file go if none of the folders listed in the `HKEY_CURRENT_USER\Software\Microsoft\SQL Server Management Studio\11.0_Config\AutomationOptions\LookInFolders` registry key exist?

Create a new folder to match the registry or add an existing directory to that registry key?

**Comment by gandarez** [comment]
Your windows has to be at least one SQL Server Management Studio installed.

You can look at the top level `KEY_CURRENT_USER\Software\Microsoft\SQL Server Management Studio\` to find out which version is installed.

**Comment by DiomedesDominguez** [comment]
There isn't AutomationOptions in 13.0_Config

![wrjk f](https://cloud.githubusercontent.com/assets/4379316/20887181/f38af3ac-bacf-11e6-868f-178a18700f25.PNG)

**Comment by gandarez** [comment]
@DiomedesDominguez I think Microsoft has disabled plugins/add-ins in this version called 2016.

**Comment by veeprox** [comment]
I manually created those folders/keys but couldn't get it working either

**Comment by gandarez** [comment]
I didn't find any documentation about add-ins for SSMS 2016.

**Comment by frackham** [comment]
Same - has anyone got this working in 2016?

**Comment by gandarez** [comment]
Just released a new version to support v2012+

Download and follow the instructions
https://github.com/gandarez/ssms-wakatime/releases/tag/v2.0.0
