### ISSUE TITLE
Support for SSMS 2016

### ISSUE THREAD

**Issue by veeprox** [gandarez/ssms-wakatime#8]
Hi everyone,

I tried following the instructions on the help page and replaced "11_config" with "13_config" but not luck. Has anyone else had any luck getting that to work?

I start SSMS but i never get asked to enter an API key.

**Comment by gandarez** [comment]
It seems SSMS 2016 does not support plugins.

**Comment by alexinea** [comment]
Does this plugin support for SSMS 17.x, version after SSMS2016?

**Comment by gandarez** [comment]
Didn't have time to test it

**Comment by mabubakarriaz** [comment]
when are we getting support for SSMS 2016/2017 ?
has anyone managed a work around? please confirm steps. Thank you

**Comment by UziTech** [comment]
I found this forum suggesting a way to create extensions for ssms 2016 (and possibly 2017)

https://www.sqlservercentral.com/Forums/1802009/Developing-Extensions-for-SSMS-2016

I haven't tried it myself but probably a good place to start

**Comment by mpearon** [comment]
Are there any plans for WakaTime to host an installable extension for this?

**Comment by gandarez** [comment]
Just released a new version to support v2012+

Download and follow the instructions
https://github.com/gandarez/ssms-wakatime/releases/tag/v2.0.0

**Comment by hubbardsw** [comment]
New version does not work, installs fine, doesnt log at all

**Comment by gandarez** [comment]
@hubbardsw it has been tested under SSMS 2016 and there wasn't any error. Could you please share your `ActivityLog.xml` file?

**Comment by UziTech** [comment]
It doesn't error for me but it doesn't seem to be recording anything on my wakatime dashboard

**Comment by gandarez** [comment]
Unblocking the library solved this issue.

**Comment by UziTech** [comment]
How do we unblock it. Mine still isn't showing up in the dashboard.

I also tried removing it and the config file from `%USERPROFILE%` and it didn't ask me for the api key.

**Comment by gandarez** [comment]
> How do we unblock it. Mine still isn't showing up in the dashboard.
> 
> I also tried removing it and the config file from `%USERPROFILE%` and reinstalling it and it didn't ask me for the api key.

Try this https://github.com/gandarez/ssms-wakatime/issues/1#issuecomment-206484919

**Comment by UziTech** [comment]
That worked!
